from tkinter import *
root=Tk()
root.title("The Endless Dice Game")
root.geometry("500x500")
root.configure(background="Purple")
label_player_1=Label(root,text="Player1",bg="Violet",fg="black")
label_player_2=Label(root,text="PLayer2",bg="Violet",fg="black")
label_player_1.place(relx=0.3,rely=0.5,anchor=CENTER)
label_player_2.place(relx=0.7,rely=0.5,anchor=CENTER)
label_score_1=Label(root,bg="Violet",fg="black")
label_score_2=Label(root,bg="Violet",fg="black")
label_score_1.place(relx=0.3,rely=0.7,anchor=CENTER)
label_score_2.place(relx=0.7,rely=0.7,anchor=CENTER)
label_random_num=Label(root,bg="Violet",fg="black")
label_random_num.place(relx=0.5,rely=0.6,anchor=CENTER)
root.mainloop()